In [1]:
import numpy as np
import torch

# 1. Creating a 3x3 matrix of random numbers
np_array = np.random.rand(3, 3)
pt_tensor = torch.rand(3, 3)

# 2. Basic Math (Element-wise addition)
np_result = np_array + 5
pt_result = pt_tensor + 5

In [2]:
np_array

array([[0.79704808, 0.59797664, 0.78709608],
       [0.66110934, 0.75883243, 0.55849891],
       [0.24013536, 0.71570651, 0.15761986]])

In [3]:
pt_tensor

tensor([[0.7961, 0.6695, 0.4583],
        [0.4069, 0.4617, 0.2770],
        [0.7503, 0.8577, 0.9876]])

In [4]:
zero_tensor = torch.zeros(5,5)
zero_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [5]:
import torch
print(torch.cuda.is_available())

True


In [6]:
# Move the tensor to the GPU
pt_tensor_gpu = pt_tensor.to('cuda')

In [7]:
pt_tensor_gpu

tensor([[0.7961, 0.6695, 0.4583],
        [0.4069, 0.4617, 0.2770],
        [0.7503, 0.8577, 0.9876]], device='cuda:0')

In [8]:
# Try to convert the GPU tensor back to NumPy
pt_tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
##AIzaSyAOShOR7uhL3wT195GnPwbpY36KmZRvmpQ

In [10]:
!pip install -q -U google-generativeai

In [11]:
import google.generativeai as genai
from google.colab import userdata

# 1. Fetch the key securely from the Secrets Manager
API_KEY = userdata.get('GOOGLE_API_KEY')

# 2. Configure the SDK
genai.configure(api_key=API_KEY)

# 3. Load the model (We'll use 'gemini-1.5-flash' for speed)
model = genai.GenerativeModel('gemini-1.5-flash')

print("Ready to generate!")

Ready to generate!


In [12]:
# List all models available to your API key
for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash-exp
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.0-flash-lite-preview-02-05
models/gemini-2.0-flash-lite-preview
models/gemini-exp-1206
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image-preview
models/gemini-2.5-flash-image
models/gemini-2.5-flash-preview-09-2025
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-resear

In [19]:
# 1. Update the model name to one from your list
model = genai.GenerativeModel('models/gemini-flash-latest')

# 2. The confusing code and prompt are the same as before
cryptic_code = "print('\n'.join([' '.join(['*' for _ in range(i)]) for i in range(1, 6)]))"

prompt = f"""
You are an expert Python tutor. Explain what the following code does in one sentence,
then show what the output would look like.

Code:
{cryptic_code}
"""

# 3. Send it to the model
response = model.generate_content(prompt)

# 4. Print the result
print(response.text)

This code constructs a list of increasing strings of space-separated asterisks (from one to five stars) and then prints each string on a new line, forming a right-aligned triangle.

***

## Output:

```
*
* *
* * *
* * * *
* * * * *
```


In [20]:
# 1. Get input dynamically from the user
user_code = input("Paste the code you want explained: ")

# 2. Construct the prompt using the user's input
prompt = f"""
You are an expert Python tutor. Explain what the following code does in one sentence,
then show what the output would look like.

Code:
{user_code}
"""

# 3. Generate and print
response = model.generate_content(prompt)
print("\n--- AI Explanation ---\n")
print(response.text)

Paste the code you want explained: [x**2 for x in range(10) if x % 2 == 0]

--- AI Explanation ---

As an expert Python tutor, I can explain that this code uses a list comprehension to efficiently generate a new list.

### Explanation (One Sentence)

This list comprehension constructs a list containing the squares of all even integers between 0 and 9, inclusive.

***

### Output

```
[0, 4, 16, 36, 64]
```
